spring:
  application:
    name: Auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: Auth
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      SECRET_KEY: f/P4JXtQmXhOfSd4U4Yq0sz8dhCO2jWDYhsUo2YyH2o=
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
